# Site settings
title: Dwj Blog
SEOTitle: 杜万江的博客 | DWJ Blog
header-img: img/home-bg.jpg
email: duwangjiang@gmail.com
description: "关于后端与开发、黑客与码农 | 杜万江，Java Web & Hacker enthusiast | 这里是 @DWJ杜万江 的个人博客，记录自己的成长过程。"
keyword: "杜万江, DWJ杜万江, DWJ, @DWJ, 杜万江的博客, duwanjiang Blog, 博客, 个人网站, 互联网, Web, Java, 服务端, 破解"
url: "https://duwanjiang.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false

weibo_username:     s453600196
zhihu_username:     s453600196
github_username:    duwanjiang
twitter_username:   duwanjiang
#facebook_username:  s453600196
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: duwanjiang

# Gitalk settings
gitalk_clientId: ed4f9aea65c2a8100dbc       
gitalk_clientSecret: 50e4384ef26be345c8d0b1c117000400de3ab50e
gitalk_owner: duwanjiang
gitalk_repo: myblog_comment

# Netease settings
#netease_sourceId: 
#netease_productKey: 


# Comment type settings , for instance: gitalk,disqus,netease
comment_type: gitalk



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: duwanjiang.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>生命不息，学习不止"
sidebar-avatar: /img/avatar-dwj-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
         title: "Hux黄玄",
         href: "https://huangxuan.me/"
    },{
        title: "田甜",
        href: "http://maplebeats.com"
    }
]
